working_directory = "/home/radim/dev/"

[font]
size = 12.0

[font.normal]
family = "Inconsolata"

[shell]
program = "/usr/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "Full"
# startup_mode = "Maximized"
dynamic_title = true
